INSERT INTO `eswaps_content` (`content_name`, `content_type`, `content_status`) VALUES ('homebannertexts', 'page', 'y');
UPDATE `eswaps_client_module_category` SET `nTmp_status`=0 WHERE `nCategoryId`=1;
UPDATE `eswaps_client_module_category` SET `nTmp_status`=0 WHERE `nCategoryId`=5;
UPDATE `eswaps_client_module_category` SET `nTmp_status`=0 WHERE `nCategoryId`=6;
UPDATE `eswaps_client_module_category` SET `nTmp_status`=0 WHERE `nCategoryId`=8;
UPDATE `eswaps_client_module_category` SET `nTmp_status`=0 WHERE `nCategoryId`=9;
UPDATE `eswaps_client_module_category` SET `nParentId`=21, `nCposition` = 'Footer' WHERE `nCategoryId`=15;
UPDATE `eswaps_client_module_category` SET `nParentId`=21, `nCposition` = 'Footer' WHERE `nCategoryId`=16;
UPDATE `eswaps_client_module_category` SET `nParentId`=21, `nCposition` = 'Footer' WHERE `nCategoryId`=17;
UPDATE `eswaps_client_module_category` SET `nParentId`=21, `nCposition` = 'Footer' WHERE `nCategoryId`=18;
DELETE FROM `eswaps_client_module_category` WHERE `nCategoryId` = 14;
DELETE FROM `eswaps_client_module_category` WHERE `nCategoryId` = 20;


INSERT INTO `eswaps_content` (`content_id`, `content_name`, `content_type`) 
				VALUES (44, 'newofferReceived', 'email'),
				(45, 'counterOfferReceived', 'email'),
                                (46, 'offerAccepted', 'email');

INSERT IGNORE INTO `eswaps_content_lang` (`content_id`, `lang_id`, `content`, `content_title`) VALUES

( 46, 6, '\r\n    <span id="result_box" class="short_text" lang="de"><span class="hps">Ihr Angebot</span> <span class="hps">durch</span> <span class="hps">akzeptiert</span></span> {user_name}.<span id="result_box" class="" lang="fr"><span class="hps">S\'il vous pla&icirc;t</span> <span class="hps">vous connecter pour voir</span> <span class="hps">les</span> <span class="hps">d&eacute;tails de l\'offre</span></span>.<br /><br />Vielen Dank<br /><br />{SITE_NAME} Crew.| {SITE_URL}        \r\n\r\n', 'Ihr Angebot an Akzeptierte {SITE_NAME}'),
	
	( 46, 1, '\r\n    Your offer accepted by {user_name}.Please login to view the offer details.<br /><br />The {SITE_NAME} Crew | {SITE_URL}              \r\n\r\n', 'Your Offer Accepted  at {SITE_NAME}'),
	( 46, 2, '\r\n    <span id="result_box" class="short_text" lang="fr"><span class="hps">Votre offre</span> <span class="hps">accept&eacute;e par</span></span> {user_name}.<br />    \r\n<div id="gt-res-content" class="almost_half_cell">        \r\n<div dir="ltr" style="zoom:1"><span id="result_box" class="" lang="fr"><span class="hps">S\'il vous pla&icirc;t</span> <span class="hps">vous connecter pour voir</span> <span class="hps">les</span> <span class="hps">d&eacute;tails de l\'offre.</span></span></div></div><br />Merci!<br /><br />{SITE_NAME} Crew | {SITE_URL}                              \r\n\r\n', 'Votre offre acceptée au {SITE_NAME}'),
	( 46, 5, '\r\n    Your offer accepted by {user_name}.<span id="result_box" class="short_text" lang="es"><span class="hps">Inicia sesi&oacute;n para</span> <span class="hps">ver</span> <span class="hps">los</span> <span class="hps">detalles de la oferta</span></span>.<br /><br />Gracias<br /><br />{SITE_NAME} Tripulacion.| {SITE_URL}    \r\n\r\n', 'Su oferta aceptada por {SITE_NAME}'),
	( 44, 1, '\r\n      New offer has been received from {receiver_user_name}.Please login to view the offer details.<br /><br />The {SITE_NAME} Crew | {SITE_URL}<br />                      \r\n\r\n', 'New offer recieved at {SITE_NAME}'),
	( 44, 2, '\r\n      \r\n<div style="display: inline-block;" id="gt-input-tool">    \r\n<div id="itamenu"><span class="ita-kd-inputtools-div"></span></div></div>    \r\n<div id="gt-src-c" class="g-unit">    \r\n<div id="gt-src-p"> </div> </div>     \r\n<div id="gt-res-content" class="almost_half_cell">    \r\n<div dir="ltr" style="zoom:1"><span id="result_box" class="short_text" lang="fr"><span class="hps">Nouvelle</span> <span class="hps">offre a</span> <span class="hps">&eacute;t&eacute; re&ccedil;ue</span></span> {receiver_user_name}.<span id="result_box" class="" lang="fr"><span class="hps">S\'il vous pla&icirc;t</span> <span class="hps">vous connecter pour voir</span> <span class="hps">les</span> <span class="hps">d&eacute;tails de l\'offre.</span></span><br /></div></div><br />Merci!<br /><br />&nbsp;{SITE_NAME} Crew | {SITE_URL}              \r\n\r\n', 'Nouvelle offre au recieved {SITE_NAME}'),
	( 44, 5, '\r\n    <span id="result_box" class="short_text" lang="es"><span class="hps">Nueva</span> <span class="hps">oferta ha sido</span> <span class="hps">recibida de</span></span> {receiver_user_name}.<span id="result_box" class="short_text" lang="es"><span class="hps">Inicia sesi&oacute;n para</span> <span class="hps">ver</span> <span class="hps">los</span> <span class="hps">detalles de la oferta</span></span>.<br /><br />Gracias<br /><br />&nbsp;{SITE_NAME} Tripulacion.| {SITE_URL}              \r\n\r\n', 'New offer recieved at {SITE_NAME}'),
	( 44, 6, '\r\n    <span id="result_box" class="short_text" lang="de"><span class="hps">Neues Angebot</span> <span class="hps">wurde von</span> <span class="hps">empfangen worden</span></span> {receiver_user_name}.<span id="result_box" class="short_text" lang="de"><span class="hps">Bitte</span> <span class="hps">anmelden, um die</span> <span class="hps">Details zu sehen</span> <span class="hps">Angebot</span></span>.<br /><br />Vielen Dank<br /><br />{SITE_NAME} Crew.| {SITE_URL}              \r\n\r\n', 'Neues Angebot erhielt bei {SITE_NAME}'),
	( 45, 1, '\r\n  Counter offer has been received from {receiver_user_name}.Please login to view the offer details.<br /><br />The {SITE_NAME} Crew | {SITE_URL}                              \r\n\r\n', 'Counter offer recieved at {SITE_NAME}'),
	( 45, 2, '\r\n    <span id="result_box" class="short_text" lang="fr"><span class="hps">Contre-offre</span> <span class="hps">a &eacute;t&eacute; re&ccedil;ue</span></span> {receiver_user_name}.<br />  \r\n<div style="display: inline-block;" id="gt-input-tool">  \r\n<div id="itamenu"><span class="ita-kd-inputtools-div"></span></div></div>  \r\n<div id="gt-src-c" class="g-unit">  \r\n<div id="gt-src-p"> </div> </div>   \r\n<div id="gt-res-content" class="almost_half_cell">  \r\n<div dir="ltr" style="zoom:1"><span id="result_box" class="" lang="fr"><span class="hps">S\'il vous pla&icirc;t</span> <span class="hps">vous connecter pour voir</span> <span class="hps">les</span> <span class="hps">d&eacute;tails de l\'offre.</span></span></div></div><br />Merci!<br /><br />{SITE_NAME} Crew | {SITE_URL}                  \r\n\r\n', 'Contre-offre à recieved {SITE_NAME}'),
	( 45, 5, '\r\n      \r\n<div style="display: inline-block;" id="gt-input-tool">  \r\n<div id="itamenu"><span class="ita-kd-inputtools-div"></span></div></div>  \r\n<div id="gt-src-c" class="g-unit">  \r\n<div id="gt-src-p"> </div> </div>   \r\n<div id="gt-res-content" class="almost_half_cell">  \r\n<div dir="ltr" style="zoom:1"><span id="result_box" class="short_text" lang="es"><span class="hps">Contra-oferta</span> <span class="hps">se ha recibido</span></span> {receiver_user_name}.<span id="result_box" class="short_text" lang="es"><span class="hps">Inicia sesi&oacute;n para</span> <span class="hps">ver</span> <span class="hps">los</span> <span class="hps">detalles de la oferta</span></span>.<br /></div></div><br />Gracias<br /><br />{SITE_NAME} Tripulacion.| {SITE_URL}                  \r\n\r\n', 'Contra-oferta recibió en {SITE_NAME}'),
	( 45, 6, '\r\n      \r\n<div style="display: inline-block;" id="gt-input-tool">  \r\n<div id="itamenu"><span class="ita-kd-inputtools-div"></span></div></div>  \r\n<div id="gt-src-c" class="g-unit">  \r\n<div id="gt-src-p"> </div> </div>   \r\n<div id="gt-res-content" class="almost_half_cell">  \r\n<div dir="ltr" style="zoom:1"><span id="result_box" class="short_text" lang="de"><span class="hps">Gegenangebot</span> <span class="hps">wurde von</span> <span class="hps">empfangen worden</span></span> {receiver_user_name}.<span id="result_box" class="" lang="fr"><span class="hps">S\'il vous pla&icirc;t</span> <span class="hps">vous connecter pour voir</span> <span class="hps">les</span> <span class="hps">d&eacute;tails de l\'offre</span></span>.<br /></div></div><br />Vielen Dank<br /><br />{SITE_NAME} Crew.| {SITE_URL}', 'Gegenangebot erhielt beit {SITE_NAME}');
	

